name: Automatically approve and merge safe dependency updates

# To be used with:
# on:
# - pull_request_target
# permissions:
#   contents: write
#   pull-requests: write

on:
- workflow_call

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: act
      if: ${{ (github.event.pull_request.user.login == 'renovate[bot]' && (
                startsWith(github.head_ref, 'renovate/org.jenkins-ci.plugins-plugin-')) ||
                startsWith(github.head_ref, 'renovate/io.jenkins.tools.incrementals-git-changelist-maven-extension-')) ||
              (github.event.pull_request.user.login == 'dependabot[bot]' && (
                startsWith(github.head_ref, 'dependabot/maven/org.jenkins-ci.plugins-plugin-')) ||
                startsWith(github.head_ref, 'dependabot/maven/io.jenkins.tools.incrementals-git-changelist-maven-extension-')) }}
      run: |
        gh pr review --approve "$PR_URL"
        gh pr merge --squash --auto "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
